#!/usr/bin/env bash
# STUDIO Correction Detection Hook
# Detects when user modifies generated code and suggests learning
#
# Triggered by: PostToolUse on Edit
# Purpose: Identify patterns in user corrections for Memory rule suggestions

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STUDIO_DIR="${STUDIO_DIR:-studio}"

# Read input from stdin (hook context)
INPUT=$(cat)

# Extract file path from tool input
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || echo "")

if [[ -z "$FILE_PATH" ]]; then
    exit 0
fi

# Find active manifest
find_active_manifest() {
    local latest=""
    local latest_time=0

    for manifest in "${STUDIO_DIR}"/projects/*/tasks/*/manifest.json; do
        if [[ -f "$manifest" ]]; then
            local status
            status=$(jq -r '.status // "UNKNOWN"' "$manifest" 2>/dev/null)

            # Check if this task is active (not complete, not aborted)
            case "$status" in
                BUILDING|READY_TO_BUILD|PLANNING)
                    local updated
                    updated=$(jq -r '.updated_at // ""' "$manifest" 2>/dev/null)
                    if [[ -n "$updated" ]]; then
                        local ts
                        if [[ "$(uname)" == "Darwin" ]]; then
                            ts=$(date -j -f "%Y-%m-%dT%H:%M:%S" "${updated%.*}" +%s 2>/dev/null || echo 0)
                        else
                            ts=$(date -d "$updated" +%s 2>/dev/null || echo 0)
                        fi
                        if [[ "$ts" -gt "$latest_time" ]]; then
                            latest_time=$ts
                            latest=$manifest
                        fi
                    fi
                    ;;
            esac
        fi
    done

    echo "$latest"
}

MANIFEST=$(find_active_manifest)

if [[ -z "$MANIFEST" ]] || [[ ! -f "$MANIFEST" ]]; then
    # No active task - not a correction scenario
    exit 0
fi

TASK_DIR=$(dirname "$MANIFEST")

# Check if this file was generated by STUDIO in current task
GENERATED=$(jq -r --arg path "$FILE_PATH" '
  .artifacts_produced // [] |
  map(select(.path == $path)) |
  length
' "$MANIFEST" 2>/dev/null || echo "0")

if [[ "$GENERATED" -eq 0 ]]; then
    # File was not generated by STUDIO - not a correction
    exit 0
fi

# This is a correction! User is modifying generated code

# Check for git diff to see what changed
DIFF=""
if command -v git &> /dev/null; then
    DIFF=$(git diff HEAD -- "$FILE_PATH" 2>/dev/null || echo "")
fi

# Log the correction
CORRECTIONS_FILE="${STUDIO_DIR}/memory/corrections.md"
mkdir -p "$(dirname "$CORRECTIONS_FILE")"

NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Initialize corrections file if needed
if [[ ! -f "$CORRECTIONS_FILE" ]]; then
    cat > "$CORRECTIONS_FILE" << 'EOF'
# User Corrections

This file tracks corrections users make to generated code.
Patterns here can be converted to Memory rules.

---

EOF
fi

# Append correction
cat >> "$CORRECTIONS_FILE" << EOF

## Correction: ${NOW}

**File:** \`${FILE_PATH}\`
**Task:** $(jq -r '.task_id // "unknown"' "$MANIFEST")

EOF

if [[ -n "$DIFF" ]]; then
    cat >> "$CORRECTIONS_FILE" << EOF
**Changes:**
\`\`\`diff
${DIFF}
\`\`\`

EOF
fi

# Output context for Claude to analyze
cat << EOF
{"additionalContext": "USER CORRECTION DETECTED

The user modified a file that STUDIO generated: ${FILE_PATH}

This may indicate a pattern worth learning. Consider:

1. PATTERN ANALYSIS
   Review the change to identify if this is:
   - A bug fix (STUDIO made an error)
   - A style preference (user prefers different approach)
   - A project convention (should be a Memory rule)

2. IF PATTERN DETECTED
   Suggest adding to Memory:

   Example: If user always changes \`const\` to \`let\` in certain contexts,
   suggest adding to studio/memory/global.md:
   - Use 'let' for variables that may be reassigned

3. ASK FOR CONFIRMATION
   Before adding any Memory rules, ask the user:
   \"I noticed you changed [X] to [Y]. Should I remember this as a preference?\"

File changed: ${FILE_PATH}
${DIFF:+Diff available in corrections.md}"}
EOF
